version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - run:
          name: Which ruby
          command: ruby --version

workflows:
  ruby_CI: 
    jobs:
      - build
