version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - run:
          name: Ruby version
          command: ruby --version
workflows:
  ruby_ci: 
    jobs:
      - build
