version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
jobs:
  ruby_CI:
    docker:
      - image: cimg/ruby:3.1.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
workflows:
  ruby_CI: 
    jobs:
      - build
