version: 2.1

jobs:
  build:
    docker:
      - image: rails:5.0
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install the needed gems
          command: bundle install --without production
workflows:
  ruby_ci: 
    jobs:
      - build
