version: 2.1

jobs:
  build:
    docker:
      - image: ruby:2.7.5
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install the needed gems
          command: bundle install --without production
      - run:
          name: Migrate db
          command: rails db:migrate
      - run:
          name: Run rails test
          command: cd test; rails test
workflows:
  ruby_ci: 
    jobs:
      - build
